In [1]:
import pandas as pd
rg= pd.read_csv (r'C:\Users\USER\Downloads\nutr.csv' , low_memory = False)

In [2]:
rg.info()

<class 'pandas.DataFrame'>
RangeIndex: 110880 entries, 0 to 110879
Data columns (total 33 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   YearStart                   110880 non-null  int64
 1   YearEnd                     110880 non-null  int64
 2   LocationAbbr                110880 non-null  str
 3   LocationDesc                110880 non-null  str
 4   Datasource                  110880 non-null  str
 5   Class                       110880 non-null  str
 6   Topic                       110880 non-null  str
 7   Question                    110880 non-null  str
 8   Data_Value_Unit             4620 non-null    str
 9   Data_Value_Type             110880 non-null  str
 10  Data_Value                  97666 non-null   float64
 11  Data_Value_Alt              97666 non-null   float64
 12  Data_Value_Footnote_Symbol  13214 non-null   str
 13  Data_Value_Footnote         13214 non-null   str
 14  Low_Confidence_Limit        97666 non-null   float64
 15  High_Confidence_Limit       97666 non-null   float64
 16  Sample_Size                 97666 non-null   float64
 17  Total                       3960 non-null    str
 18  Age(years)                  23760 non-null   str
 19  Education                   15840 non-null   str
 20  Sex                         7920 non-null    str
 21  Income                      27720 non-null   str
 22  Race/Ethnicity              31680 non-null   str
 23  GeoLocation                 108864 non-null  str
 24  ClassID                     110880 non-null  str
 25  TopicID                     110880 non-null  str
 26  QuestionID                  110880 non-null  str
 27  DataValueTypeID             110880 non-null  str
 28  LocationID                  110880 non-null  int64
 29  StratificationCategory1     110880 non-null  str
 30  Stratification1             110880 non-null  str
 31  StratificationCategoryId1   110880 non-null  str
 32  StratificationID1           110880 non-null  str
dtypes: float64(5), int64(3), str(25)
memory usage: 27.9 MB

In [14]:
rg.describe()

,YearStart,YearEnd,Data_Value,Data_Value_Alt,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size,LocationID
count,108864.000000,108864.000000,95653.000000,95653.000000,95653.000000,95653.000000,95653.000000,108864.000000
mean,2017.236111,2017.236111,31.799558,31.799558,27.325917,36.846004,1862.053454,31.351852
std,3.931702,3.931702,10.363245,10.363245,10.136447,11.302788,2391.373447,18.183468
min,2011.000000,2011.000000,0.900000,0.900000,0.300000,3.000000,50.000000,1.000000
25%,2014.000000,2014.000000,24.900000,24.900000,20.300000,29.300000,484.000000,17.000000
50%,2017.000000,2017.000000,31.700000,31.700000,27.200000,36.600000,1047.000000,30.500000
75%,2020.250000,2020.250000,37.500000,37.500000,33.200000,42.900000,2269.000000,45.000000
max,2024.000000,2024.000000,85.300000,85.300000,74.700000,92.400000,43776.000000,78.000000

In [3]:
rg.isnull().sum()
#this will print the count of null values in each column

YearStart                          0
YearEnd                            0
LocationAbbr                       0
LocationDesc                       0
Datasource                         0
Class                              0
Topic                              0
Question                           0
Data_Value_Unit               106260
Data_Value_Type                    0
Data_Value                     13214
Data_Value_Alt                 13214
Data_Value_Footnote_Symbol     97666
Data_Value_Footnote            97666
Low_Confidence_Limit           13214
High_Confidence_Limit          13214
Sample_Size                    13214
Total                         106920
Age(years)                     87120
Education                      95040
Sex                           102960
Income                         83160
Race/Ethnicity                 79200
GeoLocation                     2016
ClassID                            0
TopicID                            0
QuestionID                         0
DataValueTypeID                    0
LocationID                         0
StratificationCategory1            0
Stratification1                    0
StratificationCategoryId1          0
StratificationID1                  0
dtype: int64

In [4]:
#we fill all units because there're many null values  
print( "null values for Data_Value_Unit are: ") 
print (rg['Data_Value_Unit'].isnull().sum()) 
rg['Data_Value_Unit'] = rg['Data_Value_Unit'].fillna('NAN')
print ("null values after filling are : ") 
print (rg['Data_Value_Unit'].isnull().sum())

null values for Data_Value_Unit are:
106260
null values after filling are :
0

In [5]:
#before_after
print("missing values for geolocation were before : ") 
print(rg['GeoLocation'].isnull().sum())
print("missing values for geolocation now : ")
rg = rg.dropna(subset=['GeoLocation'])
print(rg['GeoLocation'].isnull().sum() )

missing values for geolocation were before :
2016
missing values for geolocation now :
0

In [6]:
print("values that are duplicated : ") 
print(rg.duplicated().sum()) 
rg= rg.drop_duplicates()
print( " values that are duplicated now" )  
print (rg.duplicated().sum())

values that are duplicated :
0
 values that are duplicated now
0

In [7]:
print("no values are duplicated")

no values are duplicated

In [8]:
rg.info()

<class 'pandas.DataFrame'>
Index: 108864 entries, 0 to 110879
Data columns (total 33 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   YearStart                   108864 non-null  int64
 1   YearEnd                     108864 non-null  int64
 2   LocationAbbr                108864 non-null  str
 3   LocationDesc                108864 non-null  str
 4   Datasource                  108864 non-null  str
 5   Class                       108864 non-null  str
 6   Topic                       108864 non-null  str
 7   Question                    108864 non-null  str
 8   Data_Value_Unit             108864 non-null  str
 9   Data_Value_Type             108864 non-null  str
 10  Data_Value                  95653 non-null   float64
 11  Data_Value_Alt              95653 non-null   float64
 12  Data_Value_Footnote_Symbol  13211 non-null   str
 13  Data_Value_Footnote         13211 non-null   str
 14  Low_Confidence_Limit        95653 non-null   float64
 15  High_Confidence_Limit       95653 non-null   float64
 16  Sample_Size                 95653 non-null   float64
 17  Total                       3888 non-null    str
 18  Age(years)                  23328 non-null   str
 19  Education                   15552 non-null   str
 20  Sex                         7776 non-null    str
 21  Income                      27216 non-null   str
 22  Race/Ethnicity              31104 non-null   str
 23  GeoLocation                 108864 non-null  str
 24  ClassID                     108864 non-null  str
 25  TopicID                     108864 non-null  str
 26  QuestionID                  108864 non-null  str
 27  DataValueTypeID             108864 non-null  str
 28  LocationID                  108864 non-null  int64
 29  StratificationCategory1     108864 non-null  str
 30  Stratification1             108864 non-null  str
 31  StratificationCategoryId1   108864 non-null  str
 32  StratificationID1           108864 non-null  str
dtypes: float64(5), int64(3), str(25)
memory usage: 28.2 MB

In [9]:
print("Before:", rg["LocationAbbr"].dtype)

rg["LocationAbbr"] = rg["LocationAbbr"].astype("category")

print("After:", rg["LocationAbbr"].dtype)

Before: str
After: category

In [10]:
# to clear text 
rg['LocationDesc'] = rg['LocationDesc'].str.strip().str.lower()

In [11]:
print(rg['LocationDesc'].head())

0    alabama
1    alabama
2    alabama
3    alabama
4    alabama
Name: LocationDesc, dtype: str

In [12]:
print(rg)

        YearStart  YearEnd LocationAbbr    LocationDesc  \
0            2011     2011           AL         alabama
1            2011     2011           AL         alabama
2            2011     2011           AL         alabama
3            2011     2011           AL         alabama
4            2011     2011           AL         alabama
...           ...      ...          ...             ...
110875       2024     2024           WI       wisconsin
110876       2024     2024           WY         wyoming
110877       2024     2024           GU            guam
110878       2024     2024           PR     puerto rico
110879       2024     2024           VI  virgin islands

                                        Datasource                    Class  \
0       Behavioral Risk Factor Surveillance System  Obesity / Weight Status
1       Behavioral Risk Factor Surveillance System  Obesity / Weight Status
2       Behavioral Risk Factor Surveillance System  Obesity / Weight Status
3       Behavioral Risk Factor Surveillance System  Obesity / Weight Status
4       Behavioral Risk Factor Surveillance System  Obesity / Weight Status
...                                            ...                      ...
110875  Behavioral Risk Factor Surveillance System        Physical Activity
110876  Behavioral Risk Factor Surveillance System        Physical Activity
110877  Behavioral Risk Factor Surveillance System        Physical Activity
110878  Behavioral Risk Factor Surveillance System        Physical Activity
110879  Behavioral Risk Factor Surveillance System        Physical Activity

                               Topic  \
0            Obesity / Weight Status
1            Obesity / Weight Status
2            Obesity / Weight Status
3            Obesity / Weight Status
4            Obesity / Weight Status
...                              ...
110875  Physical Activity - Behavior
110876  Physical Activity - Behavior
110877  Physical Activity - Behavior
110878  Physical Activity - Behavior
110879  Physical Activity - Behavior

                                                 Question Data_Value_Unit  \
0       Percent of adults aged 18 years and older who ...             NAN
1       Percent of adults aged 18 years and older who ...             NAN
2       Percent of adults aged 18 years and older who ...             NAN
3       Percent of adults aged 18 years and older who ...             NAN
4       Percent of adults aged 18 years and older who ...             NAN
...                                                   ...             ...
110875  Percent of adults who engage in no leisure-tim...               %
110876  Percent of adults who engage in no leisure-tim...               %
110877  Percent of adults who engage in no leisure-tim...               %
110878  Percent of adults who engage in no leisure-tim...               %
110879  Percent of adults who engage in no leisure-tim...               %

       Data_Value_Type  ...                               GeoLocation  \
0                Value  ...             (32.840571122, -86.631860762)
1                Value  ...             (32.840571122, -86.631860762)
2                Value  ...             (32.840571122, -86.631860762)
3                Value  ...             (32.840571122, -86.631860762)
4                Value  ...             (32.840571122, -86.631860762)
...                ...  ...                                       ...
110875           Value  ...   (44.39319117400049, -89.81637074199966)
110876           Value  ...  (43.23554134300048, -108.10983035299967)
110877           Value  ...                   (13.444304, 144.793731)
110878           Value  ...                   (18.220833, -66.590149)
110879           Value  ...                   (18.335765, -64.896335)

        ClassID TopicID QuestionID  DataValueTypeID  LocationID  \
0           OWS    OWS1       Q036            VALUE           1
1           OWS    OWS1       Q036            VALUE           1
2           OWS    OWS1       Q036            VALUE           1
3           OWS    OWS1       Q036            VALUE           1
4           OWS    OWS1       Q036            VALUE           1
...         ...     ...        ...              ...         ...
110875       PA     PA1       Q047            VALUE          55
110876       PA     PA1       Q047            VALUE          56
110877       PA     PA1       Q047            VALUE          66
110878       PA     PA1       Q047            VALUE          72
110879       PA     PA1       Q047            VALUE          78

        StratificationCategory1     Stratification1 StratificationCategoryId1  \
0                        Income   $15,000 - $24,999                       INC
1                        Income   $25,000 - $34,999                       INC
2                        Income   $35,000 - $49,999                       INC
3                        Income   $50,000 - $74,999                       INC
4                        Income  $75,000 or greater                       INC
...                         ...                 ...                       ...
110875           Race/Ethnicity  Non-Hispanic Other                      RACE
110876           Race/Ethnicity  Non-Hispanic Other                      RACE
110877           Race/Ethnicity  Non-Hispanic Other                      RACE
110878           Race/Ethnicity  Non-Hispanic Other                      RACE
110879           Race/Ethnicity  Non-Hispanic Other                      RACE

       StratificationID1
0                INC1525
1                INC2535
2                INC3550
3                INC5075
4              INC75PLUS
...                  ...
110875           RACEOTH
110876           RACEOTH
110877           RACEOTH
110878           RACEOTH
110879           RACEOTH

[108864 rows x 33 columns]

In [13]:
rg.describe()

,YearStart,YearEnd,Data_Value,Data_Value_Alt,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size,LocationID
count,108864.000000,108864.000000,95653.000000,95653.000000,95653.000000,95653.000000,95653.000000,108864.000000
mean,2017.236111,2017.236111,31.799558,31.799558,27.325917,36.846004,1862.053454,31.351852
std,3.931702,3.931702,10.363245,10.363245,10.136447,11.302788,2391.373447,18.183468
min,2011.000000,2011.000000,0.900000,0.900000,0.300000,3.000000,50.000000,1.000000
25%,2014.000000,2014.000000,24.900000,24.900000,20.300000,29.300000,484.000000,17.000000
50%,2017.000000,2017.000000,31.700000,31.700000,27.200000,36.600000,1047.000000,30.500000
75%,2020.250000,2020.250000,37.500000,37.500000,33.200000,42.900000,2269.000000,45.000000
max,2024.000000,2024.000000,85.300000,85.300000,74.700000,92.400000,43776.000000,78.000000